cedricpinson/osgjs

examples/shadowmap/index.html
examples/shadowmap/main.js
sources/osgShadow/shaders/esm.glsl
sources/osgShadow/shaders/evsm.glsl
sources/osgShadow/shaders/shadowsCastFrag.glsl
tutorials/12_Basic_Shadow/index.html
tutorials/12_Basic_Shadow/main.js

Fixes shadowMap esm clamp, evsm params
Adds shadow sample missing es5-6 shim
Adds basicScene url parameter to switch for light leak test scene (filtermode)
Add tutorial

Fixes all other techniques and add basic tutorial

---

sources/osgShadow/ShadowMap.js
tests/osgShadow/ShadowMap.js

- better near/far bounding, use of those for the optimized case
- more robust transformation handling for spot
- DRY code (near/far, lightup, single epsilon)

Fixes spot light frustum optimizatin when inside scene bbox

---

examples/picking/main.js
sources/osg/BoundingSphere.js
sources/osg/KdTree.js
sources/osg/KdTreeBuilder.js
sources/osg/KdTreeRayIntersector.js
sources/osg/KdTreeSphereIntersector.js
sources/osgUtil/LineSegmentIntersector.js
sources/osgUtil/SphereIntersector.js
sources/osgUtil/TriangleIntersector.js
sources/osgUtil/TriangleSphereIntersector.js
sources/osgUtil/osgUtil.js
tests/osg/KdTree.js

Maybe it requires a test and an example.
But it's here for code review.

Adds triangle sphere intersection support

---

sources/osgGA/OrbitManipulatorHammerController.js

If fixes camera navigation for computer that both supports mouse and touch events

Filter mouse event triggered by hammer

---

Gruntfile.js
sources/osgShader/Compiler.js
sources/osgShader/node/shadows.js
sources/osgShadow/shaders/esm.glsl
sources/osgShadow/shaders/evsm.glsl
sources/osgShadow/shaders/pcf.glsl
sources/osgShadow/shaders/shadowsReceiveMain.glsl
sources/osgShadow/shaders/vsm.glsl

Shadow Receivers position on Shadows Light Space is now computed in

---

sources/osgShader/Compiler.js

After a talk with @Kuranes , we decided to remove the useless declare function (as they only called getOrCreate function anyway).
+ it poped up some small typo/bugs, so it was a good idea.

Removes useless compiler code

---

LICENSE

Changed License to MIT

---

examples/animation/main.js
sources/osgAnimation/AnimationAttribute.js
sources/osgAnimation/RigTransformHardware.js
sources/osgAnimation/osgAnimation.js
sources/osgShader/Compiler.js
sources/osgShader/ShaderGenerator.js
sources/osgShader/node.js
sources/osgShader/node/animation.js
sources/osgShader/node/data.js
sources/osgShader/node/skeletal.glsl
sources/osgShader/nodeFactory.js
sources/osgShader/osgShader.js
sources/osgShader/shaderLib.js

- Optimizes Heavily shader code, reusable BoneMatrix result transform
- Adds Size uniform parameter for Array of uniform from Compiler/Node/shaderGraph
- Sort Shader Attributes inside the DeclareGlobal Compiler code (and beautifies)

Adds Animation to shader vertex graph

---

examples/shader-generator/CustomCompiler.js
sources/osgShader/Compiler.js
sources/osgShader/node/Node.js
sources/osgShader/node/data.js
sources/osgShader/node/operations.js
sources/osgShader/nodeFactory.js
tests/osgShader/Compiler.js

Adds More checks on node request/usage
Adds varyings check between shader stage
Adds Comments
Adds new Kind of variables: Outputs (glFragColor, glPointsize, glPosition)

Adds More checks on node request/usage

---

sources/osg/Quat.js
tests/osg/Quat.js

Fix Typo on quat:nlerp shortest path branch variable

---

sources/osg/State.js
sources/osg/Texture.js

Optimizes out all shadow cast passes texture bind

Makes sure texture bind null doesn't do anything

---

.editorconfig

http://editorconfig.org/ for editor plugin list to install

[#93766344] Adds EditorConfig file which should be supported by all editor around

---

.editorconfig
examples/shadowmap/main.js
sources/osgShader/Compiler.js
sources/osgShader/ShaderGenerator.js
sources/osgShader/ShaderProcessor.js
sources/osgShader/node/noise.glsl
sources/osgShader/node/shadows.js
sources/osgShader/osgShader.js
sources/osgShader/shaderLib.js
sources/osgShadow/ShadowCastAttribute.js
sources/osgShadow/ShadowMap.js
sources/osgShadow/ShadowReceiveAttribute.js
sources/osgShadow/ShadowSettings.js
sources/osgShadow/ShadowTexture.js
sources/osgShadow/shaders/esm.glsl
sources/osgShadow/shaders/evsm.glsl
sources/osgShadow/shaders/hash.glsl
sources/osgShadow/shaders/pcf.glsl
sources/osgShadow/shaders/poissonPCF.glsl
sources/osgShadow/shaders/shadowsCastFrag.glsl
sources/osgShadow/shaders/tapPCF.glsl
sources/osgShadow/shaders/vsm.glsl

Fix useless shadow texture binding during cast
Removes useless uniforms for none/pcf
Add shadow offset rotation

[#97604240] Fix shadow texture uniform warning

---

sources/osg/State.js
sources/osg/Texture.js

Details here: https://code.google.com/p/chromium/issues/detail?id=533345&thanks=533345&ts=1442573130

[#103208722] Reverts the not binding texture null

---

sources/osgShader/Compiler.js
sources/osgShader/ShaderGenerator.js
sources/osgShader/ShaderGeneratorProxy.js
sources/osgShadow/ShadowCastCompiler.js
sources/osgShadow/ShadowCastShaderGenerator.js
sources/osgShadow/ShadowMap.js
sources/osgShadow/ShadowSettings.js
sources/osgShadow/osgShadow.js

Greatly Reduces number of shaders created when multiple light or multiple materials to one per kind of shadow.

[#103333138] Adds ShadowCast Compiler

---

sources/osg/Camera.js
sources/osg/RenderStage.js
sources/osgViewer/Renderer.js
sources/osgViewer/Viewer.js
tutorials/13_ScreenShot/index.html
tutorials/13_ScreenShot/main.js

Using Camera FinalDrawCallBack mechanism
Now can take screenshot using glReadPixel, freeing the need for
preserveDrawingBuffer performance impacts
And do other operation (texture copy or oth) on each camera final draw

Adds screenshot tutorial

---

sources/osgShadow/ShadowCasterVisitor.js
sources/osgShadow/ShadowMap.js
sources/osgShadow/osgShadow.js

Allows either override with user provided visitor, false (disable any visitor) or defaut visitor (which handles lights, subscene with rtt, transparent nodes)

Adds ShadowCasterVisitor as easy override by user

---

sources/osgUtil/DisplayNodeGraphVisitor.js
sources/osgViewer/eventProxy/StandardMouseKeyboard.js

Tested on chrome, IE and firefox and it works (mousewheel)

Fix mousewheel

---

sources/osgShader/Compiler.js
sources/osgShader/node/morph.js
sources/osgShader/node/skinning.glsl

Removes conditional "if" in skinning and morph shaders.
Because of https://code.google.com/p/chromium/issues/detail?id=551937&thanks=551937&ts=1446742308#makechanges
The "if" for the ArrayColorEnabled wasn't problematic so far.

Removes if in vertex shader

---

sources/osgGA/OrbitManipulator.js

Simplifies the way to block the orbit y rotation

---

sources/osg/CullSettings.js
sources/osg/CullStack.js
sources/osg/CullVisitor.js
sources/osg/CullingSet.js
sources/osg/Polytope.js
sources/osgViewer/Renderer.js

Cullsettings being allocated each camera cullvisits
CullingSet stack reserve "cursor" wasn't rersetted to 0
Those were the last vec2/3/4 & Matrix Leaks during render loop.
/!\ changes in polytope/planes

[#DEV-6320] Fixes MemeLeaks

---

sources/osgShadow/ShadowMap.js

It was inheriting whatever was the "default state" osgjs defined

[#DEV-6348] Fixes wrong shadow blend/depth state

---

sources/osgAnimation/RigGeometry.js

Not a big fan of the copy-paste, but there's no workaround as the part that needs to be changed is inside the for loop

Compute the bounding box for non influenced vertices of a RigGeometry

---

sources/osgShader/node/functions.glsl
sources/osgUtil/ParameterVisitor.js
sources/osgWrappers/serializers/osg.js

Handles very bright linear pixel (linear to srgb)

---

sources/osg/CullStack.js
sources/osg/CullVisitor.js
sources/osg/RenderBin.js
sources/osg/RenderStage.js
sources/osgUtil/osgPool.js

Removes GC pressure by reusing previously allocated objects
Vec3 at Each pop/push modelview
RenderStage is created at each camera with framebuffer cullvisitor pass.

[#DEV-6828] Bugfix/memleaks

---

sources/osgGA/CADManipulator.js
sources/osgGA/CADManipulatorHammerController.js
sources/osgGA/CADManipulatorStandardMouseKeyboardController.js
sources/osgGA/OrbitManipulator.js
sources/osgGA/OrbitManipulatorLeapMotionController.js
sources/osgGA/OrbitManipulatorStandardMouseKeyboardController.js
sources/osgGA/osgGA.js

Adds new CAD Manipulator

---

sources/osg/Geometry.js
sources/osg/KdTreeBuilder.js
sources/osg/KdTreeRayIntersector.js
sources/osg/KdTreeSphereIntersector.js
sources/osg/Node.js
sources/osgAnimation/MorphGeometry.js
sources/osgAnimation/RigGeometry.js
sources/osgAnimation/UpdateMorph.js
sources/osgUtil/LineSegmentIntersector.js
sources/osgUtil/NodeGizmo.js
sources/osgUtil/SphereIntersector.js
sources/osgUtil/TriangleIntersector.js
sources/osgUtil/TriangleSphereIntersector.js
sources/osgWrappers/serializers/osgAnimation.js

Now the widget size doesn't depend of the width-height ratio and the canvas size.
Stops reading directly width and height attribute on canvas too (for
performance).

Improves the screen size normalization of the gizmo

---

package.json

Grunt 1.0 is incompatible avec our current setup,
add a version limit in package.json to limit to pre 1.0

Fixes  npm install and update

---

sources/osgViewer/Viewer.js
tests/osgViewer/Viewer.js

Once context Lost, prevent any further render, inform osgjs client code with a callback
Otherwise client may continue to ask new renders and thus getting
endless errors.

[#DEV-7341] Handles Better Webgl Context Lost

---

sources/osgViewer/Viewer.js

https://mozvr.github.io/webvr-spec/#dom-vrdisplay-requestpresent

Fixes minor webvr api changes

---

sources/osg/Program.js

Handles now all cases
uniform float        ubones [6];
uniform float        ubones[6];
uniform float        ubones;

Fixes uniform array regexp

---

sources/osgShader/Compiler.js

According to RedBook computed color in lighting should be 
finalColor = primaryColor ( all lighting stuff using materials) * textureColor + secondaryColor.
That long standing bug made the textured objects appear more lighted than they should.
Easy to see if using texture + material with ambient component + ambient light.

Fix for wrong lighting when using textures

---

examples/shadowmap/main.js
sources/osg/Camera.js
sources/osg/RenderStage.js
sources/osg/TimerGPU.js
sources/osg/osg.js

Adds a Timer GPU using webgl extenstion https://www.khronos.org/registry/webgl/extensions/EXT_disjoint_timer_query/
Have to call it before and after a set of gl calls to get a timer.
```js
TimerGPU.instance().start('mypostproc');
glcalls...
TimerGPU.instance().end('mypostproc');
```

[#DEV-7321] Adds TimerGPU

---

sources/osg/KdTreeRayIntersector.js
sources/osgViewer/Viewer.js

makes it easier to hook a function so that we can mirror something on the screen

Moves submitFrame in frame function for easier hook

---

sources/osgUtil/NodeGizmo.js

The gizmo is more flexible for example you can set a flag on a node that only says "you can rotate me in x, and translate me in x and z".

Makes the gizmo more flexible

---

Gruntfile.js
package.json
sources/osg/BlendColor.js

- Needs to add jsdoc comments on files to have a good documentation :)

Adds documentation js

---

examples/webVR/main.js
sources/osgViewer/Viewer.js

Need to get promises to get correct moment when we have the hmd available

[#D3D-2400] Uses HMD VR promises

---

sources/osgShader/node/colorEncode.glsl

It seems like a copy/paste error as 255^3 = 16581375 and not 160581375

Fixed error in color encode

---

examples/performance/index.html
examples/performance/main.js
webpack.config.js

add gui and option to be able to test more performances related renderings

Improves performance sample

---

sources/osgText/Text.js

Text needs to do is own traversal in order to keep track of modelview matrix

Fixes text traversal

---

sources/osg/Geometry.js
sources/osg/Image.js
sources/osg/Matrix.js
sources/osg/Notify.js
sources/osg/Program.js
sources/osg/Shader.js
sources/osg/State.js
sources/osg/TimerGPU.js
sources/osgShader/ShaderProcessor.js
sources/osgViewer/Viewer.js

uses ?GLSLOptimizer=1 to use glsl optimizer
if you want to see the shader results use &log=info

Adds optional url option to use glsl optimizer

---

sources/osg/RenderLeaf.js
sources/osg/State.js
sources/osg/StateSet.js

The hash method was not robust enough

Fixes the method used to detect stateset changed

---

sources/osg/PrimitiveFunctor.js
sources/osg/TriangleIndexFunctor.js

@cedricpinson I didn't change the API

Adds drawElement offset support in Triangle functor

---

sources/osg/Light.js

Adds Stricter Light Check/type in OSGJS so that adding new light is easier

[#D3D-2523] Strenghtens light type and check

---

sources/osg/AutoTransform.js

Add checks for modelviewMatrix in order to recompute attitude of AutoTransforms.

Fix for Autotransforms in Rtt's

---

examples/pbr/index.html
examples/pbr/main.js

Adds a loading message when a glTF scene is selected.

Adds loading message to the PBR example

---

examples/pbr/Environment.js
examples/pbr/EnvironmentCubeMap.js
examples/pbr/EnvironmentPanorama.js
examples/pbr/IntegrateBRDF.js
examples/pbr/main.js
sources/osgDB/Input.js
sources/osgDB/osgDB.js
sources/osgDB/requestFile.js
sources/osgDB/zlib.js

Next needs to build some environment and provides url to tests them

Adds package environment zip

---

sources/osgAnimation/BasicAnimationManager.js
sources/osgShader/CompilerVertex.js

stopAllAnimations is not reset anything, it just remove the active channels targets.

Adds helper to reset stacked

---

examples/shadowmap/main.js
sources/osg/Light.js
sources/osgShader/Compiler.js
sources/osgShader/CompilerFragment.js
sources/osgShader/node/shadows.js
sources/osgShadow/ShadowMap.js
sources/osgShadow/ShadowMapAtlas.js
sources/osgShadow/ShadowReceiveAttribute.js
sources/osgShadow/ShadowTexture.js
sources/osgShadow/ShadowTextureAtlas.js
sources/osgShadow/osgShadow.js
sources/osgShadow/shaders/pcf.glsl
sources/osgShadow/shaders/shadowLinearSoft.glsl
sources/osgShadow/shaders/shadowsReceiveMain.glsl
sources/osgShadow/shaders/tapPCF.glsl
tests/osgShader/Compiler.js

Using single texture and render target  for multiple shadow

[D3D-2581] Adds shadow Atlas

---

examples/ssao/index.html
examples/ssao/main.js
examples/ssao/shaders/blurFragment.glsl
examples/ssao/shaders/depthFragment.glsl
examples/ssao/shaders/depthVertex.glsl
examples/ssao/shaders/downsampleFragment.glsl
examples/ssao/shaders/ssaoFragment.glsl

Implements, as an example, the SSAO method described in [Scalable Ambient Obscurance](http://graphics.cs.williams.edu/papers/SAOHPG12/McGuire12SAO.pdf )

Adds SSAO example based on Scalable Ambient Obscurance

---

sources/osg/WebGLCaps.js

[#D3D-2935] Bans derivatives shader on apple intel

---

sources/osgShadow/shaders/shadowsReceiveMain.glsl

One brace is missing and the world collapses

[#D3D-2937] Adds one brace to shadow shader code

---

examples/pbr/main.js
sources/osg/Shader.js
sources/osgDB/FileHelper.js
sources/osgPlugins/ReaderWriterZIP.js
tests/osg/Shader.js

On ios when using too many uniform the error was not reported, it was hidden by processError. Now if the regexp does not match we return the raw error.

Fixes hidden glsl error too many uniforms on ios

---

sources/osgShader/CompilerFragment.js
sources/osgShader/node/functions.js
sources/osgShadow/shaders/shadowsReceiveMain.glsl

need to be normalized and use special code path to avoid adreno bugs

[#2945] Fixes model Normal

---

sources/osg/Light.js

Removes useless matrix in Light

---

sources/osg/Program.js
sources/osg/Shader.js

The usual pink shader is still activated, but real but failed shader is
inside a  _DEBUG so that you can debug it in  "shader editor"

Adds Easier Shader Debug

---

sources/osgShader/Compiler.js
sources/osgShader/CompilerFragment.js
sources/osgShader/CompilerVertex.js
sources/osgShadow/ShadowCastCompiler.js
sources/osgUtil/DisplayGeometryVisitor.js
sources/osgUtil/DisplayNormalVisitor.js

Improves error and warning for shader compiler

---

examples/pbr/index.html

Needs https://github.com/cedricpinson/osgjs-data/pull/1 to be merged first.

Gets gltf samples from osgjs-data

---

sources/osg/KdTree.js
sources/osg/KdTreeLineSegmentIntersector.js
sources/osg/KdTreeSphereIntersector.js
sources/osgUtil/LineSegmentIntersector.js
sources/osgUtil/TriangleLineSegmentIntersector.js
sources/osgUtil/TriangleSphereIntersector.js
sources/osgUtil/osgUtil.js
tests/osgUtil/TriangleLineSegmentIntersector.js
tests/osgUtil/osgUtilTests.js

Renames intersector

---

examples/performance/main.js

to test complex stateset use:
?stats=1&complexStateSet=true in the url

Adds options to performance to generate complex stateSet

---

sources/osg/Uniform.js

Signatures for uniform are now :
(name)
(data, name)
(name, nbItem)
If you provide an initial data, nbItem is infered depending of the item size

Improves uniform array signature

---

sources/osgViewer/webgl-utils.js

Otherwise old compute with no webgl2 supports failed because the
previous webgl detection was relying on a non standardized error message

Allows silent fail webgl2 context try

---

sources/osgShader/CompilerFragment.js

createLigthing with no light should return 0 (like before)

Fixes createLigthing

---

examples/shadowmap/main.js
sources/osgShadow/ShadowMap.js
sources/osgShadow/ShadowedScene.js

Do it once per shadowed scene instead of every shadowmap

Optimizes shadow compute caster scene bound

---

sources/OSG.js
sources/osg/KdTree.js
sources/osg/polyfill.js
sources/osgUtil/PolytopeIntersectFunctor.js

Reduces memory usage by replacing subarray by slice
Fixes polytope primiteset index

Fixes kdtree size estimation

---

examples/geometry/main.js
sources/osgShader/Compiler.js
sources/osgShader/CompilerFragment.js

Also improve geometry example to use PointSizeAttribute for points

Adds missing PointSize attribute in the compiler

---

.eslintrc.json
sources/osgPlugins/ReaderWriterGLTF.js
tests/osg/KdTree.js
tests/osgUtil/SphereIntersector.js

Adds eslint rules

---

sources/osg/notify.js

Setting a log level wouldn't work because of the mix here https://github.com/cedricpinson/osgjs/blob/master/sources/osg/osg.js#L123

Fixes log level for external calls

---

examples/pbr/main.js
examples/pbr/shaders/pbrReferenceFragment.glsl
examples/pbr/shaders/pbrReferenceVertex.glsl
examples/pbr/shaders/pbr_ue4.glsl
sources/osgPlugins/ReaderWriterGLTF.js

Support for vertex colors
Support for pbr factors
Improves specular workflow
Adds support for emissive materials

Updates GLTF implementation

---

sources/osg/notify.js

helpful to get full stack of the log call

Adds ability to enable/disable tracing to Notify

---

sources/osgStats/Counter.js
sources/osgStats/Stats.js

Adds also a way to hide a counter if not set anymore

Dont display counter if not set

---

sources/osgGA/CADManipulator.js
sources/osgGA/CADManipulatorStandardMouseKeyboardController.js

Additionally removed a unused function.

Fixes calling the PolytopeIntersector in the CADManipulator

---

package.json

By setting it to a fixed version

Fixes prettier upgrade

---

sources/osgGA/OrbitManipulatorHammerController.js
sources/osgViewer/eventProxy/Hammer.js

disables unecessary recoginzers
remove unecessary checks

Optimizes hammer listeners

---

examples/pagedlod/main.js
examples/performance/main.js
examples/shadowmap/main.js
sources/osg/BufferArray.js
sources/osg/FrameBufferObject.js
sources/osg/GLObject.js
sources/osg/Geometry.js
sources/osg/Options.js
sources/osg/Program.js
sources/osg/Shader.js
sources/osg/State.js
sources/osg/Texture.js
sources/osg/TextureCubeMap.js
sources/osg/TextureManager.js
sources/osg/TimerGPU.js
sources/osg/Utils.js
sources/osg/VertexArrayObject.js
sources/osg/WebGLCaps.js
sources/osg/osg.js
sources/osgShadow/ShadowTexture.js
sources/osgStats/Stats.js
sources/osgUtil/PolytopeIntersectFunctor.js
sources/osgViewer/View.js
sources/osgViewer/Viewer.js
sources/osgViewer/webgl-utils.js
tests/mockup/mockup.js

if lostcontext user callback return true we try to restore,
if user do need to re-provide data, he has to do by using a callback on their GLObject

Adds webglRestore support

---

sources/osgDB/Input.js
sources/osgWrappers/serializers/osg.js
sources/osgWrappers/serializers/osgAnimation.js

- reject a promise with a reason to avoid "undefined" reason
- Removes new P() when we can simply use chaining instead

Improves a bit promise warnings

---

sources/osgUtil/ComposerPostProcess.js

Absolute threshold was a bit stupid, it should be dependent of texture size.

Improves composer when fetching out of viewport

---

sources/osgShadow/ShadowMapAtlas.js

test/benchmarker on samsung s6

Reenables scissor on shadow for individual clears

---

sources/osgUtil/DisplayGeometryVisitor.js

Mostly splitting logic into a few functions

Cleans a bit DisplayGeometryVisitor

---

sources/osgShader/CompilerFragment.js
sources/osgShadow/ShadowReceiveAttribute.js
sources/osgShadow/shaders/shadowReceive.glsl
sources/osgShadow/shaders/tapPCF.glsl
tests/osgShader/Compiler.js

Allow dynamic changes without recompilation

Makes PCF an uniform instead of a Define

---

sources/osg/StateCache.js

Here the initial context for Cull StateAttribute
enable = true , mode = BACK
-> state.applyCullAttribute (enable = true, mode = back)
state.enable = true , state.mode = BACK ( buffer.enable = true, buffer.mode = back )
-> state.applyCullAttribute (enable = false, mode = back)
state.enable = true , state.mode = BACK ( buffer.enable = false, buffer.mode = back )
-> state.applyCullAttribute (enable = true, mode = front)
state.enable = true , state.mode = BACK ( buffer.enable = false, buffer.mode = front )
The code to check the update was like that:
```
if (state.enable !== enable) {
buffer.enable = enable;
data.changed = true;
}
if (!enable) return;
if (state.mode !== attribute._mode) {
buffer.mode = attribute._mode;
data.changed = true;
}
```
The logic was wrong because if new state is not …

Fixes a cache issue in CacheState

---

examples/shadowmap/custom.glsl
examples/shadowmap/debug.glsl
examples/shadowmap/main.js
examples/shadowmap/pcf.glsl
examples/shadowmap/pcss.glsl
examples/templates/Example.js
sources/osg/Program.js
sources/osgShader/ShaderGenerator.js
sources/osgShader/utils.js

demos it with 2 shader in demo shadow
examples/shadowmap?customShadow=debug
examples/shadowmap?customShadow=pcss
For now doesn't work *after* instanciation of nodes (here using the dat.gui list customShadow)

Adds custom code shader node support

---

sources/osgShader/CompilerFragment.js
sources/osgShadow/ShadowReceiveAttribute.js
sources/osgShadow/shaders/shadowReceive.glsl
sources/osgShadow/shaders/tapPCF.glsl
tests/osgShader/Compiler.js

This reverts commit babc2607618942664bdbe27f47c642d063058f78.

Revert "Makes PCF an uniform instead of a Define"

---

sources/osgShadow/ShadowMap.js
sources/osgShadow/ShadowMapAtlas.js
sources/osgShadow/ShadowedScene.js

Handles empty scene shadowing using shadow atlas

Fixes shadow atlas for empty scene

---

sources/osgShadow/ShadowMap.js

If drawing empty in shadow atlas you could end with non created uniforms

Fixes empty uniform in shadow atlas map

---

sources/osg/Program.js
sources/osg/WebGLCaps.js
sources/osg/polyfill.js
sources/osgViewer/eventProxy/StandardMouseKeyboard.js

- Refactors so that program compilation can be done async  …
- Fixes exception throwed when just including osgjs but not using it.  …
- fixes manipulator instancied but still not added an eventProxy  …
- Fixes unclean compilation case
- Fixes strange test in webglcaps, adds comment on the extension apply

Fixes errors from reports 

---

sources/osgDB/readerParser.js
sources/osgShader/ShaderProcessor.js
sources/osgUtil/ComposerPostProcess.js

Composer fix reusable

---

sources/osg/Object.js

[#WEB-9732] Renames Object to _Object to prevent shadowing webpack 

---

sources/osg/WebGLCaps.js

Some mobile reuse same driver GPUs with different capabilities
now, we double check if glsl compiler agree

Filters false positive gpu extension

---

sources/osgGA/FirstPersonManipulatorStandardMouseKeyboardController.js
sources/osgViewer/input/source/InputSourceMouse.js

Fixes walk speed direction and sensitivity for the FirstPersonManipulator
Also fixes the scrollwheel option parameter being ignored.

Fixes mouse wheel issues

---

sources/osg/polyfill.js
sources/osgViewer/input/source/InputSourceKeyboard.js

Fixes crash with IE 11 on Inputmanager Initialization

---

sources/osgViewer/input/source/InputSourceKeyboard.js

Just logging first level In the error should be enough

Fixes stringify with circular references

---

sources/osgViewer/input/source/InputSource.js
sources/osgViewer/input/source/InputSourceWebVR.js

iframe on different domains needs a allow="vr" attribute set,
otherwise it spawns an error.
Also good practice to catch fails on a promise for any reason.

Catches promise Error on pollheadsets

---

examples/pbr/main.js
examples/webVR/main.js

examples are not built, so there should be no import statement.

Fixes examples

---

package.json

Necessary to ungzip files in examples

Adds deps zlibjs removed by mistake

---

sources/osgAnimation/easing.js

Adds standard easings, linear, all powers to 8,  circle, elastic, and bounce, with all in,out,inout forms

Adds new easing functions

---

sources/osg/WebGLCaps.js

PowerVR gpu compiler has some version where it's just not there...

Checks with shader that texturecubelodext support is real

---

sources/osg/Program.js
sources/osg/Shader.js
sources/osg/notify.js
sources/osgShader/ShaderGenerator.js

- Adds shaderSync  url options
- only activates on PBR shaders

Adds Async Shader support

---

sources/osg/Program.js

When shader compilation failed, No error where given in the console

Fixes missing shader error information

---

sources/osg/Texture.js

video with mipmap filter was not getting the mipmaps  updated.

Fixes automipmapping video

---

sources/osg/Options.js

it was appended, thus under the previous part of the document

Fixes html console visibility

---

sources/osgShadow/ShadowTextureAtlas.js

Consistent viewUp instead of sometimes ViewUp etc.

Fixes inconsistent uniform naming between shadow mode
