examples/shadowmap/main.js
sources/osgShadow/ShadowMap.js
sources/osgShadow/ShadowSettings.js
sources/osgShadow/ShadowTechnique.js
sources/osgShadow/ShadowedScene.js
sources/osgShadow/shaders/shadowsReceive.glsl

Adds shadowMap filledOnce property that allows ensuring static shadowMap is built once at least after a dirty/init
Splits Shadow caster Traversal Maks in two, allowing for bounds & drawselection (you want to draw shadows, but not taking it in account in our
bounds, etc.)

Static Shadow support & better shadow traversal mask support

---

examples/shadowmap/main.js
sources/osgShader/Compiler.js
sources/osgShader/node/shadows.js
sources/osgShadow/ShadowMap.js
sources/osgShadow/shaders/shadowsCastFrag.glsl
sources/osgShadow/shaders/shadowsReceive.glsl

pack vertex xy in projection space with vertex z in view space so that we end with one vec4 instead of two. 
(firefox on windows has a stupid 8 varying limit)

Packs two vec4 into one for shadow (overcoming firefox limitations)

---

sources/osg/Texture.js

when using PagedLod Model somtimes the state is passed undefined to
relaseGLObjects function so it needs to be handeled so code wont crash

Fix code crash when state is passed as undefined to Texture module

---

sources/osgShadow/ShadowMap.js

Fix shadow texture unit wrong on recreation if not using default 4 as start

Fix shadow texture unit wrong on recreation if not using default 4

---

webpack.config.js

* name of vendors changes depending on the environment
eg: hammerjs
root (global) --> Hammer
commonjs      --> hammerjs
amd           --> hammer

Exports vendors with canonical name

---

examples/shadowmap/main.js
sources/osg/Light.js
sources/osg/RenderStage.js
sources/osgShadow/ShadowMap.js

- Add new constraint on shadowing ligh : the light node must be under shadowedScene Node in the hierarchy scene graph

[#91685744] Fixes Absolute Ref Node above light Node for shadow

---

sources/osgShadow/ShadowMap.js

Early out of shadowedscene didn't restore node mask as it should have.

Fixes shadow mapping overwriting node mask on "no shadow to draw" early out codepath

---

sources/osg/Shape.js
sources/osgUtil/Composer.js

* Much less Fragment compute per pass ( no change needed in any shader)
* Much less state change (quad is a singleton, reused whatever framebuffer size it is)

Adds FullscreenFakeQuad for faster postprocessing

---

examples/shader-generator/CustomCompiler.js
examples/shader-generator/negatif.js
examples/shader-generator/ramp.js
examples/shadow/main.js
sources/osg/Material.js
sources/osgShader/Compiler.js
sources/osgShader/ShaderProcessor.js
sources/osgShader/node/Node.js
sources/osgShader/node/data.js
sources/osgShader/node/functions.js
sources/osgShader/node/lights.js
sources/osgShader/node/operations.js
sources/osgShader/node/shadows.js
sources/osgShader/node/textures.js
sources/osgShader/nodeFactory.js
sources/osgShadow/ShadowMap.js
sources/osgUtil/Composer.js
tests/osgShader/Compiler.js

Adds Vertex Shader Graph nodes and compilation
Adds Multiple Root Graph to Shader Graph Compiler (both VS and FS)
Optimizes Vertex Shaders Generation upon data (reducing uneeded vertex attributes and varying usage and computations)
Adds New Operation Nodes : MatrixMultPosition, MatrixMultDirection
Adds News "Root" Nodes: glPosition, glPointSize
Adds New Data Nodes: "Constant"
Adds Alias Nodes: SetFromNode (alias to Add Node but with One input, one output)

Makes vertex shader composition use the shader graph compiler

---

sources/osgUtil/LineSegmentIntersector.js
tests/osgUtil/LineSegmentIntersector.js

Reverts the old "segment/sphere" intersection test.
I guess it can be still be optimized @jtorresfabra.
Here's an alternative (I don't know if it's faster though) :
```
intersects: ( function () {
var l = Vec3.create();
var dir = Vec3.create();
return function ( bsphere ) {
if ( !bsphere.valid() ) return false;
var center = bsphere.center();
var r2 = bsphere.radius2();
Vec3.sub( center, this._iStart, l );
Vec3.sub( this._iEnd, this._iStart, dir );
var t = Vec3.dot( l, dir ) / Vec3.length2( dir );
if ( t <= 0.0 ) return Vec3.length2( l ) <= r2;
if ( t >= 1.0 ) return Vec3.length2( Vec3.sub( center, this._iEnd, l ) ) <= r2;
Vec3.mult( dir, t, dir );
return Vec3.distance2( l, dir ) <= r2;
};
} )(),
```

Reverts back line segment test

---

examples/frustum-culling/main.js
sources/osg/Camera.js
sources/osg/CullVisitor.js
sources/osgViewer/Renderer.js

- Modifies frustum culling demo to follow the new convention
- Modifies Renderer so that it does call "CullVisitor::popCameraModelViewProjectionMatrix" on Main camera follows same code and can also be hooked

Removes Camera.getNearFar() and setNearFar

---

sources/osg/CullVisitor.js
sources/osgShadow/ShadowedScene.js
sources/osgViewer/Renderer.js

Probably it has been introduced as a workaround, grepping the codebase
show it's not used

Removes setCamera in CullVisitor

---

sources/osgShadow/ShadowReceiveAttribute.js

Other shadow attributes might get wrong uniform values, as they were using the same key index for the uniform cache

Fixes cloned shadow attribute overwriting uniforms 

---

Gruntfile.js
package.json
sources/osg/Notify.js
sources/osg/State.js

Now code between
```
/* develblock:start */
your code
/* develblock:end */
```
will be strip from builds except in 'grunt build-debug'

Adds webpack loader to strip debug code from build

---

examples/shadowmap/main.js
sources/osgShader/Compiler.js
sources/osgShadow/ShadowMap.js
sources/osgShadow/ShadowReceiveAttribute.js
sources/osgShadow/ShadowSettings.js
tests/osgShader/Compiler.js
tests/osgShadow/ShadowMap.js

So that shadowreceiveattribute ctor has a light number at creation.
Otherwise shadowreceiveattribute  may  be cloned without any "light" and then if using multiple shadowreceiveattribute, you'll have mutiple cloned default shadowreceiveattribute with typeMember !== key in the State.js AttributeMap
/!\ Breaking Change for all shadowmap user (lightSource of settings given to ShadowMap need a lightSource )

Makes mandatory to give a lightsource to shadowmap ctor 

---

sources/osgShader/Compiler.js
sources/osgShader/node/Node.js

Fixes wrong initial compiler flags making unessecary varyings detected
Fixes unlighted material wrong initial compiler flags making unessecary uniforms detected
by new Compiler
Fixes customVertexShader usage incorrectly making compiler check on varyings
Adds Better warning/error logs on varyings (name + type)

Fixes wrong initial compiler flags making unessecary varyings detected

---

sources/osgGA/FirstPersonManipulator.js
sources/osgGA/FirstPersonManipulatorHammerController.js
sources/osgGA/FirstPersonManipulatorStandardMouseKeyboardController.js
sources/osgGA/OrbitManipulator.js
sources/osgGA/OrbitManipulatorHammerController.js
sources/osgGA/OrbitManipulatorStandardMouseKeyboardController.js
sources/osgGA/osgGA.js

These stuffs have been bothering me since ages :).
commit 1 : if we rotate with one finger and then adds a second one, it now moves to pan mode.
It's something that has been bothering me A LOT on mobile since I often failed to correctly pan on first try.
commit 2 : fps manipulator is fully operational on mobile now.
Also, firstPersonManipulator's computeHomePosition now set the distance (speed) depending of the home bounding box (that way if we use the FPS manipulator in the exemples there's no need to set manually the distance to get correct pan speed).
commit 3 : It's faster when we zoom out. Maybe it's not the best way to do it but it helps a lot for now.
commit 4: Kind of experimental, if we zoom a lot and hit the minDistance pivot point, I added an option to move the pivot itself and …

Improves manipulators

---

.eslintrc
Gruntfile.js
package.json

Sample results: 
```
Running "eslint:target" (eslint) task
sources/osg/Geometry.js
118:17  error  "attribute" is defined but never used        no-unused-vars
119:17  error  "attributeList" is defined but never used    no-unused-vars
120:17  error  "attributesCache" is defined but never used  no-unused-vars
sources/osg/Matrix.js
983:17  error  Opening curly brace does not appear on the same line as controlling statement  brace-style
sources/osg/Node.js
270:49  error  halt is already declared in the upper scope  no-shadow
sources/osg/Shader.js
111:28  error  Missing radix parameter  radix
sources/osg/Texture.js
24:21  error  Texture was used before it was defined  no-use-before-define
sources/osg/Uniform.js
139:34  error  value is already declared in the upper scope  no-shadow
253:34  error …
```

Adds eslint with rules inferred from jshint

---

tests/index.html
webpack.config.js

Transition to Q library of promises to Bluebird left a missing external dependency check. Now bluebird won't be embedded anymore in the osg.js build

[#103412958] Fixes Bluebird embedding in the osgjs build

---

sources/osgViewer/Viewer.js
sources/osgViewer/eventProxy/GamePad.js

The check performed on argumentEventBackend.device.enable could never be false so it could never be disabled. Additionally check isValid within the GamePad class itself so we can always alter the _enable prop to control the feature.

[#100330416] Makes gamepad controls disableable

---

sources/osgShadow/shaders/shadowsCastFrag.glsl
sources/osgShadow/shaders/shadowsReceiveMain.glsl

That makes sure that plane perpendicular to light doesn't flicker due to
selfshadowing and 1 = dot(Normal, Light) using a min bias

Adds min bias with enhanced precision

---

examples/shadowmap/main.js
sources/osg/WebGLCaps.js
sources/osgShadow/ShadowMap.js
sources/osgShadow/ShadowReceiveAttribute.js
sources/osgShadow/shaders/shadowsReceiveMain.glsl
sources/osgViewer/View.js

Makes it now viewer independant, can be called even before osg viewer
initialisation, uses its own canvas.
Viewer still needs to enable extension for their canvas
Adds platform information to start degrading gracefull only on defect gpu/os/browser instead of degrading everyone.

Makes WebGLCaps a singleton

---

sources/osgUtil/Composer.js
sources/osgViewer/eventProxy/StandardMouseKeyboard.js

@jtorresfabra I broke the mousewheel with the last commit.
@cedricpinson we should enforce 'use strict' usage maybe

Fixes mousewheel warning

---

sources/osg/WebGLCaps.js

Nodejs environment may call webglCaps but it needs some meaningful
capabilities to be able to run nodejs apps built on osgjs

Adds Min Reqs to WebglCaps

---

sources/osg/Camera.js
sources/osg/FrameBufferObject.js
tests/mockup/mockup.js
tests/osg/FrameBufferObject.js
tests/osg/osgTests.js

Allows to correctly remove/delete fbo/rbo, if user want to resize a render target

[#DEV-6234] Adds Camera::resetAttachments

---

sources/osg/State.js

Latest compositor uses fakeFullscreenQuad which
doesn't need any matrix to render on screen, but
osgjs code alway tried to bind a projectionMatrix

Fixes null projectionMatrix GL Calls

---

sources/osg/Options.js
sources/osg/WebGLCaps.js
sources/osgViewer/webgl-utils.js

Chrome and Firefox have 100% support but both behind browser flags, so we can just use webgl2 context when available. 
It's progressive enhancement, as it mocks webgl1 extension and capabilities check so that it's all
transparent osgjs side.
Adds a  webglCaps.isWebGL2() in case of webgl2 only need to check feature when we'll progessively add them (texturearray, texture3d, ubo, etc.)

Adds Webgl2 Support When available

---

sources/osgShadow/shaders/shadowsReceiveMain.glsl

Seems using shadowUV projected values cause some strange error on
intel hd derivatives, switched to using the depth as it's a easier
values to derive

[#DEV-6286] Fixes intel derivatives GPU

---

sources/osg/WebGLCaps.js

New webglCaps initializing the webgl context, but failing when browser
not supporting it, was doing it so without being controllable, thus
preventing user from controlling the "no webgl" error message.
No it reverts to previous user controllable scheme

[#DEV-6449] Fix uncontrollable Body overwrite

---

sources/osg/Image.js
tests/osg/Image.js

Fixes previous osg Texture code which was using a very relaxed test to check if it has an HTML image or a OSG image inside, which gives incorrect results to user with ublock extension.
Ublock Extension add a HTML image "isReady" method, with exaclty the same name as osg Image leading to current code believing incorrectly that the "wrapped by ublock Image" is an osg Image, or is not a HTML image thus never loading it in a gpu texture.
Any inconsiderate browser extension wrapping the Image html element,
and there may be even more in the future when browser will freeze the
'natives' objects like Image, thus needs a "detection by feature" as
last resort of the isReady method.

[DEV-6488] Robustifies osg.image.isReady

---

benchmarks/index.html
benchmarks/osg/Geometry.js
benchmarks/osg/mainPerformance.js
benchmarks/osg/osgBenchmarks.js
benchmarks/reportStats.js
examples/picking/main.js
sources/osg/Geometry.js
sources/osgAnimation/MorphGeometry.js
sources/osgUtil/LineSegmentIntersector.js
sources/osgUtil/PolytopeIntersector.js
sources/osgUtil/SphereIntersector.js
sources/osgUtil/TriangleSphereIntersector.js

On the picking example with the highly tesselated sphere, the computation of box : 
- ~470 ms
- now, ~95ms
To give an overview of why "writing in array is slower" An alternate version (simpler but slower, ~145ms))
````
for ( var idx = 0, l = vertexes.length; idx < l; idx += itemSize ) {
var v0 = vertexes[ idx ];
var v1 = vertexes[ idx + 1 ];
var v2 = vertexes[ idx + 2 ];
if ( v1 > min[ 0 ] ) min[ 0 ] = v1;
if ( v1 < max[ 0 ] ) max[ 0 ] = v1;
if ( v2 > min[ 1 ] ) min[ 1 ] = v2;
if ( v2 < max[ 1 ] ) max[ 1 ] = v2;
if ( v3 > min[ 2 ] ) min[ 2 ] = v3;
if ( v3 < max[ 2 ] ) max[ 2 ] = v3;
}
```
The 3 times are very consistent

Morph box faster box

---

sources/osgUtil/DisplayNormalVisitor.js

Now it works if the matrix has some rotation in it too.
I don't handle the non-uniform scale case for now but it should be enough for debug.

Improves scale world computation for normal debug

---

sources/osgShadow/ShadowMap.js
sources/osgViewer/Viewer.js

rendering same frame N times wasn't possible as timestamp was
automatically updated, canvas size checked and manipulator might have intervened too.
Idea is to be able to optimize that use case further. Faster
cull/update/draw as nothing but some shader uniform change between frames

[#DEV-6816] Adds viewer::getUpdateVisitor Accessor And Fixes shadowmap RenderSize

---

sources/osgShader/Compiler.js

In order to be able to make custom shadow computation the final shadow
effect computation is now a separate method that can be overridden.

[DEV-7032] Allows custom shadow effect shader

---

sources/osg/RenderLeaf.js
sources/osg/StateGraph.js

When using insertStateSet and RenderLeaf use this codepath
```
var hash = state.getStateSetStackHash();
if ( previousHash !== hash ) {
this._parent.moveStateGraph( state, undefined, this._parent.parent );
state.applyStateSet( this._parent.stateset );
previousHash = hash;
}
```
We where pushing all StateSet from the stateGraph ( from current to root
) on State.
So for example we had something like that in state after rendering
multiple RenderLeaf
[ 25, 39, 46, 567, 248, 251, 569, 565, 55, 257, 39, 46, 567, 248, 251,
569, 565, 55, 257, ... ]
the sequence [ 39, 46, 567, 248, 251, 569, 565, 55, 257 ] was repeated
because of moveStateGraph( state, undefined, this._parent.parent );
Actually this code path needs to re apply State's StateSet if an
insertStateSet has been used but does not need to …

Removes extra pushStateSet when using insertStateSet

---

sources/osgGA/OrbitManipulator.js

It was too application-specific as sometimes, it didn't do what
the function was meant to do.

Removes setEyePosition orbit limitation

---

sources/osgShader/Compiler.js
tests/osg/Image.js

compiler traverse nodes making sure we follow multiple output, thus taking precedence over order of node inside the node graph, making impossible optimisation like reuse of temp variable implicitely

[DEV-7142] Remove Temp var shader node reuse

---

sources/osg/Program.js
sources/osg/Uniform.js

Uniforms declared like this:
`uniform float myarray[10];` or 
`uniform float myarray [10]; //note blank space before [ ` 
were not working.

Fix for uniforms declared as arrays

---

Gruntfile.js
package.json
sources/osgNameSpace.js

the require( 'version' ) was completely useless as : 
- the file doesn't exist (so the require always failed and returned undefined cf. examples where the version simply doesn't exist)
- the whole osgNameSpace file was overriden by the grunt build

Cleans osgNameSpace code

---

sources/osg/Options.js
sources/osgUtil/IntersectionVisitor.js
sources/osgUtil/NodeGizmo.js
sources/osgViewer/Viewer.js

- reset the matrix stack if we create a new visitor
- handles the case where we use the intersection visitor starting with a non-camera node
in that case, the first camera encountered was considered as absolute and it discarded the
model matrices (although the camera was relative)

Fixes intersection visitor camera

---

sources/osgViewer/Viewer.js

If there is RTTs camera below the graph, if the framebuffer size doesn't
match with the RTTs size, webgl will display a black screen.

Makes sure the viewport contains integer values

---

sources/osgGA/OrbitManipulator.js

Not sure why there were an epsilon check in the setMinDistance.

Removes epsilon check when changing min distance orbitManipulator

---

sources/osgShadow/shaders/shadowsReceiveMain.glsl

When a light is not ligthing a fragment we optimize by not computing
shadow (and avoid any acne shadow on those surface)
But we returned 1.0 which means "no shadow" which is not consistent
shadow receive function. (in fact it is "shadowed")

[D3D-2515] shadow ps must return 0 when unlighted

---

examples/pbr/main.js
examples/pbr/shaders/pbrReferenceFragment.glsl
sources/osgPlugins/ReaderWriterGLTF.js

This commit fixes some glTF loading issues and add normal Y-flipping support.
The line:
`vec3 B = -tangent.w * cross(normal, tang);`
seemed to be correct for left-handed coordinate systems.

Adds yUp normal flip support to the glTF loader

---

sources/osg/WebGLCaps.js
sources/osgShadow/shaders/shadowsReceiveMain.glsl

Removed using derivating inside a branch as it makes for undefined behavior
So the early return in the shadowmaping code in now done after
derivatives computations
see http://teknicool.tumblr.com/post/77263472964/glsl-dynamic-branching-and-texture-samplers

[#D3D-270] Fixes shadow shader non uniform flow derivatives usage

---

sources/osg/ImageStream.js

Can prevent issue such as http://stackoverflow.com/questions/10235919/the-canplay-canplaythrough-events-for-an-html5-video-are-not-called-on-firefox

Resolves video event if it is already ready

---

sources/osgNameSpace.js

Webpack 2 stopped supporting the '-loader' shortcut. When trying to require a source package of osgjs in a project using wepback 2, the build currently fails. This PR fixes that.

Removes inline webpack loaders shortcuts

---

sources/osg/Plane.js
sources/osg/Viewport.js
sources/osgUtil/PolytopeIntersector.js
sources/osgUtil/PolytopePrimitiveIntersector.js

Reduce vector allocations.
Fixes the buggy use case when there is no matrix transform in the picking path (uninitialized _iPolytope/_iReferencePlane)
Adds the cullingActive check for node intersection (like the segmentIntersector)

Cleans a few stuffs in polytope code

---

sources/osgShader/Compiler.js
sources/osgShader/CompilerFragment.js
sources/osgShader/CompilerVertex.js

Some getOrCreate were just create. Also renamed a few functions.
As a side note :
In osgjs the separation between CompilerVertex and CompilerFragment is just implicit, they are part of the same Compiler class.
Maybe it'd be nice to have a system where some functions could *only* be called from certain shader stage.
For example it's confusing that `getOrCreateModelVertex`, `getOrCreateLocalVertex`, etc... (same for normal, tangent) should only be called from the vertex stage (in the fragment we query directly the varying).
Alternatively, functions named `getOrCreateFrontBlabla` shouldn't be called from CompilerVertex.

Renames compiler shader functions

---

sources/osgShadow/shaders/shadowsReceiveMain.glsl

Spotlight shadowmatrix isn't the same as the light matrix 
(it's an optimized frustum) so dot(normal,light) may not yeld the same result in some cases
( note that the test was redundant with the "lighted" boolean we get from actual light computation, so no big loss here. )

Fixes spotlight wrong ndl earlyout

---

sources/osgGA/OrbitManipulatorStandardMouseKeyboardController.js

It prevents the focus of the canvas

Stops preventing default on mousedown

---

sources/osgUtil/Composer.js

shader is crashing if the filter is adding its own default shader_name, so by default the filter is not adding any default name

Removes default filter shader name

---

examples/ground/ground.js
sources/osg/TimerGPU.js
sources/osg/WebGLCaps.js
sources/osgViewer/webgl-debug.js

Timer query is **still** an extension in webgl2, but it shares most of the constant with the gl1 extension.
Exception is the `getQueryObjectExt` that is now `getQueryParamter` (and not `getQueryObject`)

Adds webgl2 disjoint timer query support

---

sources/osgGA/OrbitManipulator.js
tests/osgGA/OrbitManipulator.js

Fixes a case when the computer previousYaw is not exactly the same that was set on the previous frame.
this line https://github.com/cedricpinson/osgjs/blob/master/sources/osgGA/OrbitManipulator.js#L246
For example whenever we reach the limit (say 2.0), next frame the computed previousYaw could return 2.00000000001 which will make this test fail https://github.com/cedricpinson/osgjs/blob/master/sources/osgGA/OrbitManipulator.js#L275
This PR introduce a value comparison with an epsilon value to avoid this problem.

Fixes an edge case in orbitManipulator limits

---

sources/osgUtil/LineSegmentIntersector.js
sources/osgUtil/SphereIntersector.js

(the typo `this._intersections > 0` vs `this._intersections.length > 0` has a very big perf impact for some reasons)

Fixes typo in intersection visitor

---

sources/osgShader/node/functions.glsl

For some reasons, only Edge complained about that.

Fixes frontNormal name function (collision variable)

---

sources/osgDB/DatabasePager.js

Gain few cpu time ms on old mobile and lowend desktop cpu as it's called each frame.
With that commit, the function disappear from the profiler,  as it seems the native "this._pendingNodes.sort" call is not that optimized, And as it's the most common case, I think it's worth it for such a small change.

Adds earlyout on datapager sort

---

sources/osg/TimerGPU.js
sources/osgViewer/Viewer.js
sources/osgViewer/createStats.js

Alleviates performance impact of stats, alleviates readability, makes it usable on phones.
All stat is 
?stats=1
but filtered stat is 
?stats=frame
?stats=culllightsource
etc.

Adds option to filter Stats

---

sources/osgGA/CADManipulator.js
sources/osgGA/FirstPersonManipulator.js
sources/osgGA/OrbitManipulator.js

…ng multiple times the events of the controllers
These fixes also allow the users of the manipulators to override the event callbacks, otherwise new callbacks were created and some inconsistencies could happen.

Reuses controllers when initializing manipulators

---

examples/shadowmap/main.js
sources/osg/Camera.js
sources/osg/RenderStage.js
sources/osgShader/CompilerFragment.js
sources/osgShadow/ShadowMap.js
sources/osgShadow/ShadowMapAtlas.js
sources/osgShadow/ShadowTextureAtlas.js
sources/osgShadow/ShadowedScene.js
tests/mockup/mockup.js

Clears whole texture at once for shadowAtlas Avoid samsung bug on scissor+glClear
Fixes shadowAtlas recent light and compiler refactors broke it.

Clears the whole atlas at the same time

---

sources/osgUtil/PolytopeIntersector.js

The intersector function name was misspelled, causing two functions to have the same name.

Fixes PolytopeIntersector function names

---

examples/multi-viewport-rtt/main.js
sources/osg/Camera.js
sources/osg/CullVisitor.js
sources/osg/RenderBin.js
sources/osg/RenderStage.js
sources/osg/State.js
sources/osg/StateSet.js
sources/osg/Utils.js
sources/osgShader/ShaderGenerator.js
sources/osgViewer/Renderer.js
sources/osgViewer/View.js

It does not seems to have a big effect on performance sample even if it seems a bit faster on chrome and similar in firefox, but on safari it seems more interesting
this the timing of 'render' in stats
chrome:
3.6/3.7 (master)
3.3/3.45 (avoid-sparse-array)
firefox:
4.7/4.9 (master)
4.5/4.8 (avoid-sparse-array)
safari:
6.7/6.9 (master)
5.5/5.8 (avoid-sparse-array)
Also adds a better handling of Scissor

Avoids sparse array in StateSet and State

---

examples/text2D/main.js
sources/osg/BlendFunc.js
sources/osg/ColorMask.js
sources/osg/CullFace.js
sources/osg/Depth.js
sources/osg/Geometry.js
sources/osg/RenderStage.js
sources/osg/Scissor.js
sources/osg/State.js
sources/osg/StateCache.js
sources/osg/Viewport.js
sources/osg/shape.js
tests/mockup/mockup.js

Stats on differents examples
shadowmap:
before 446 gl commands
after 405 gl commands
PBR example with model lieutenant:
before 329
after 308
performance with complex stateset:
before 13345
after 10262
sketchfab https://sketchfab.com/models/49f9821876b744fab3453048185c04b6?stats=1
before 4011
after 2169
Mobile on https://sketchfab.com/models/2afd4091d395418c9107b84ad5b09cf2?stats=1 I get from
90-100ms on glframe w/o cache => final 8fps
60-70ms on glrame with cache => final 10fps

Caches Blend/Depth/CullFace/ColorMask gl state

---

sources/osg/Geometry.js

When using Morph geometry with BufferProxy the geometry does not use vao
so when we had something like:
Geometry VAO
Geomtry Non-VAO
The second geometry was changing the VAO of the first geometry. The fix
disable VAO when drawing the second geometry.

Fixes VAO with non VAO geometry

---

sources/osgUtil/NodeGizmo.js

Removing the `attachToMatrixTransform` and `attachToGeometry` functions and replacing them with `attachToNode`.
(ideally `attachToNodePath` should be prefered)

Cleans nodeGizmo attachToNode behavior

---

sources/osgGA/OrbitManipulator.js
tests/osgGA/OrbitManipulator.js

Separate pitch computation to be able to override it in sub classes.

Splits OrbitManipulator limits computation for easier overriding

---

sources/osgDB/Input.js

This was causing problems for us during cross-origin requests. It may also be a good idea to set onload handlers before starting download but it may have performance implications.

* Setting cross origin policy before starting image download.

---

sources/osg/Options.js
sources/osgGA/CADManipulatorHammerController.js
sources/osgGA/CADManipulatorStandardMouseKeyboardController.js
sources/osgGA/Controller.js
sources/osgGA/FirstPersonManipulatorDeviceOrientationController.js
sources/osgGA/FirstPersonManipulatorStandardMouseKeyboardController.js
sources/osgGA/FirstPersonManipulatorWebVRController.js
sources/osgGA/OrbitManipulatorDeviceOrientationController.js
sources/osgGA/OrbitManipulatorGamePadController.js
sources/osgGA/OrbitManipulatorHammerController.js
sources/osgGA/OrbitManipulatorStandardMouseKeyboardController.js
sources/osgGA/OrbitManipulatorWebVRController.js
sources/osgStats/Stats.js
sources/osgUtil/NodeGizmo.js
sources/osgViewer/Viewer.js
sources/osgViewer/eventProxy/DeviceOrientation.js
sources/osgViewer/eventProxy/GamePad.js
sources/osgViewer/eventProxy/Hammer.js
sources/osgViewer/eventProxy/StandardMouseKeyboard.js
sources/osgViewer/eventProxy/WebVR.js

Doing this improvement trigger some issues how events are handled in osgjs. The way events works in osgjs is through eventProxies.
eventProxies are responsible to initialize differents device and get events from them. Then we have different adapters to translate events from different device to manipulators.
On osgStats we need to pick a gl quads and scroll it if it hits. 
The problem is that manipulator is connected to StandardMouseKeyboard proxy and a mouseDown will also start to inititate a rotation on the orbit manipulator. Even if it's possible to disable the StandardMouseKeyboard proxy after the mouse down, we still have a side effect at the mouseup event because orbit manipulator has received the first mousedown. So to fix this we inject the mouseup in StandardMouseKeyboard at the …

Improves stats

---

sources/osgViewer/View.js

There were two lines with the method's names swapped.

Fixes the methods calls to flushAllDeletedGLObjects. 

---

sources/osgGA/FirstPersonManipulatorStandardMouseKeyboardController.js

It was changed when the line `this._buttonup = false;` was added. Before that, this._buttonup was set to true in the call to `this.releaseButton()`. Have you changed this intentionally?

Restores the behaviour of First Person Manipulator.

---

examples/shadowmap/main.js
sources/osg/Program.js
sources/osgShadow/ShadowMap.js
sources/osgShadow/ShadowMapAtlas.js
sources/osgShadow/ShadowTechnique.js
sources/osgShadow/ShadowedScene.js

shadow::enable or not => was meant for static or dynamic
Best to rename it shadow::setContinousUpdate
(the "real" disabling shadow is done removing the shadowedscene node)

Renames shadowEnable to isContinuousUpdate

---

examples/shadowmap/pcf.glsl
sources/osgShader/CompilerFragment.js
sources/osgShadow/ShadowMap.js
sources/osgShadow/ShadowTexture.js
sources/osgShadow/ShadowTextureAtlas.js
sources/osgShadow/shaders/shadowCast.glsl
sources/osgShadow/shaders/shadowLinearSoft.glsl
sources/osgShadow/shaders/shadowReceive.glsl
sources/osgShadow/shaders/tapPCF.glsl

For 4 shadows
- New Count       **24 uniforms.**
- Previous Count 42 Uniforms
( Removes At least 16 uniform vector, more depends on other uniforms)
Done:  
------
```
Uniform             | Before        | After
----------------------------------------------
- projection        | Mat4          |  Vec3
- view              | Mat4          | 3 Vec4
- depth range       | Vec4          |  Vec2
- shadow size       | Vec4          |  Vec2
```
IF we go Manual Packing: 25 Vector
---------
```
Uniform                | Before     | After
----------------------------------------------
- projection, bias    | vec3, float | Vec4
- range, mapSize      | vec2, vec2  | Vec4
- float jitter float  | 4 float     | vec4 
```
Side Benefit: 40 mul optimized out 
(derivated out the 0/1 and unused computation in …

Reduces shadow uniform size

---

sources/osgUtil/gizmoGeometry.js

Calling this function avoids problems when creating a new gizmo in a new glContext. The problem is that when a gizmo is created the programs in GizmoGeometry (which are global) are instantiated. After that if a new gizmo is created in a new glContext, the Gizmo Geometry tries to use the programs variables because they aren't undefined but it doesn't work since these programs are associated to the first glContext,

Adds a function to reset the programs variables in GizmoGeometry

---

sources/osgShadow/ShadowMap.js

user code could have wrong camera reference. 
It fixes "stats" that could be non existant on camera shadow, as they were done on "camera.setinitalDrawCallback". As camera could be deleted/renewed, that callback wouldn't be called.

Removes unecessary camera delete/recreation

---

sources/osg/polyfill.js

Old browser without map, set or uint8, we don't even try, so no need
to do exception.
(osgjs dev users has to filter on his side usage of osgjs)

Fixes exception on old browsers

---

sources/osgShadow/ShadowMap.js

When disabling/enabling shadow, non shadow atlas was getting leftover
framebuffer binded to wrong (previous) texture shadow

Fixes framebuffer leftover

---

sources/osg/RenderBin.js
sources/osg/RenderStage.js
sources/osgViewer/Viewer.js

When the canvas is removed the PooledResource objects in RenderBin and RenderStage are not cleaned and they keep references to BufferArrays so the memory is not freed. 
Adding this two methods allows to free that memory.

Adds a method to RenderBin and RenderStage to clean their PooledResource objects

---

sources/osg/Program.js

With spectorJS enabled, it was segfaulting when we got "error in
shader" instead of going to failsafe  because we tried to access it
before we compiled the failsafe.

Fixes shader error handling when spector enabled

---

sources/osgViewer/input/source/InputSourceKeyboard.js

- check for key before trying to lowerCase it
- removed the error logging now that error is traced back to cause

Fixes IE11 missing key on event when hitting shift

---

sources/osg/Program.js

Since decoupling program compilation/linking state, the context
restore didn't work

Fixes context restoring not able to compile program again

---

sources/osgPlugins/ReaderWriterGLTF.js

Before my fix, ReaderWriterGLTF only read either *emissiveTexture* or *emissiveFactor*.
This bug made the emissive texture not appear on PBR models.
Now, ReaderWriterGLTF reads both variables.

Fixes the missing emissive texture during GLTF file reading.

---

sources/osgViewer/View.js

No more polling canvas size on chrome each frame
(and other browser next, and degrades to current way of polling if it doesn't exists)
( see https://developers.google.com/web/updates/2016/10/resizeobserver )

Adds resizeObserver support
